/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthenticatedLocadorasRouteImport } from './routes/_authenticated.locadoras'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedFinalizadosRouteImport } from './routes/_authenticated.finalizados'
import { Route as AuthenticatedAbandonadosRouteImport } from './routes/_authenticated.abandonados'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated.contratos.index'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated.contratos.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLocadorasRoute = AuthenticatedLocadorasRouteImport.update({
  id: '/locadoras',
  path: '/locadoras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinalizadosRoute =
  AuthenticatedFinalizadosRouteImport.update({
    id: '/finalizados',
    path: '/finalizados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAbandonadosRoute =
  AuthenticatedAbandonadosRouteImport.update({
    id: '/abandonados',
    path: '/abandonados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abandonados': typeof AuthenticatedAbandonadosRoute
  '/finalizados': typeof AuthenticatedFinalizadosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/locadoras': typeof AuthenticatedLocadorasRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abandonados': typeof AuthenticatedAbandonadosRoute
  '/finalizados': typeof AuthenticatedFinalizadosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/locadoras': typeof AuthenticatedLocadorasRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/abandonados': typeof AuthenticatedAbandonadosRoute
  '/_authenticated/finalizados': typeof AuthenticatedFinalizadosRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/locadoras': typeof AuthenticatedLocadorasRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abandonados'
    | '/finalizados'
    | '/home'
    | '/locadoras'
    | '/auth/verify'
    | '/auth/'
    | '/contratos/$id'
    | '/contratos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abandonados'
    | '/finalizados'
    | '/home'
    | '/locadoras'
    | '/auth/verify'
    | '/auth'
    | '/contratos/$id'
    | '/contratos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/abandonados'
    | '/_authenticated/finalizados'
    | '/_authenticated/home'
    | '/_authenticated/locadoras'
    | '/auth/verify'
    | '/auth/'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/locadoras': {
      id: '/_authenticated/locadoras'
      path: '/locadoras'
      fullPath: '/locadoras'
      preLoaderRoute: typeof AuthenticatedLocadorasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finalizados': {
      id: '/_authenticated/finalizados'
      path: '/finalizados'
      fullPath: '/finalizados'
      preLoaderRoute: typeof AuthenticatedFinalizadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/abandonados': {
      id: '/_authenticated/abandonados'
      path: '/abandonados'
      fullPath: '/abandonados'
      preLoaderRoute: typeof AuthenticatedAbandonadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAbandonadosRoute: typeof AuthenticatedAbandonadosRoute
  AuthenticatedFinalizadosRoute: typeof AuthenticatedFinalizadosRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLocadorasRoute: typeof AuthenticatedLocadorasRoute
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbandonadosRoute: AuthenticatedAbandonadosRoute,
  AuthenticatedFinalizadosRoute: AuthenticatedFinalizadosRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLocadorasRoute: AuthenticatedLocadorasRoute,
  AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
